### ISSUE TITLE
map not showing up

### ISSUE THREAD

**Issue by iQoo** [JackDougherty/public-toilets-copenhagen#5]
Hi Jack, 

Thank you for the example. When I click on your gh pages (https://jackdougherty.github.io/public-toilets-copenhagen/), the map did not show up on the right hand side. Any suggestions?

Thank you in advance.
Qoo

**Comment by JackDougherty** [comment]
Hi IQoo -- I have removed this repository since it was a temporary example for someone else.

See better examples at Data Visualization For All http://DataVizForAll.org

Jack
